#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/cc3dvasctumor.sh -t cc3dvasctumor \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none
